import type { Activity } from "@/types/activity";

export const defaultActivities: Activity[] = [
  {
    id: 1,
    ActivityID: "ACT-9001",
    ActivityType: "Phone Call",
    ActivityDate: "2026-07-06T13:42:00",
    Subject: "Monthly feedstock volume discussion",
    Summary:
      "Supplier confirmed ability to deliver 250 tonnes/month of HDPE regrind.",
    ActivityDescription:
      "Discussed monthly feedstock volumes with Elena. Supplier can deliver 250 tons/month of HDPE regrind with consistent moisture below 2%. Current sorting line handles contamination well.",
    Company: { Id: 1, Title: "Nordic Polymers AB" },
    Contact: { Id: 101, Title: "Elena Lindström" },
    Deal: { Id: 0, Title: "PL-1042" },
    ActivityOwner: { Id: 12, Title: "Elena Lindström" },
    ActionRequired: true,
    NextAction: "Request material sample",
    NextActionDate: "2026-07-13",
    ActionStatus: "Open",
    ActionOutcome: "Positive",
    KeyDecisions: [
      "Proceed with HDPE regrind as primary feedstock for PL-1042",
      "Lock provisional volume at 250 tonnes/month",
    ],
    AgreedActions: [
      { text: "Supplier to send moisture certification", dueDate: "2026-07-10" },
      { text: "Commercial to draft updated supply schedule", status: "Open" },
    ],
    Risks: ["Seasonal volume dip possible in Q4"],
    LinkedDocuments: [
      {
        Title: "PL-1042_Feedstock-Spec.02.pdf",
        DocCategory: "Technical",
        Revision: "02",
        DealId: "PL-1042",
      },
    ],
    LinkedDeals: [{ Id: 0, Title: "PL-1042" }],
    LinkedContacts: [{ Id: 101, Title: "Elena Lindström" }],
  },
  {
    id: 2,
    ActivityID: "ACT-9002",
    ActivityType: "Email",
    ActivityDate: "2026-07-06T09:15:00",
    Subject: "Throughput reconciliation signed off",
    Summary: "Client confirmed acceptance of Q3 throughput report at 94.2%.",
    ActivityDescription:
      "HDPE Batch A conversion held at 94.2%. Client confirmed acceptance of Q3 throughput report via email reply.",
    Company: { Id: 1, Title: "Nordic Polymers AB" },
    Contact: { Id: 101, Title: "Elena Lindström" },
    Deal: { Id: 0, Title: "PL-1042" },
    ActivityOwner: { Id: 12, Title: "Elena Lindström" },
    ActionRequired: false,
    NextAction: "",
    NextActionDate: "",
    ActionStatus: "Completed",
    ActionOutcome: "Positive",
    KeyDecisions: ["Q3 throughput figures accepted without revision"],
    AgreedActions: [],
    Risks: [],
    LinkedDocuments: [
      {
        Title: "PL-1042_Financial-Invoice.01 Q3 Report.pdf",
        DocCategory: "Financial",
        Revision: "01",
        DealId: "PL-1042",
      },
    ],
    LinkedDeals: [{ Id: 0, Title: "PL-1042" }],
    LinkedContacts: [{ Id: 101, Title: "Elena Lindström" }],
  },
  {
    id: 3,
    ActivityID: "ACT-9003",
    ActivityType: "Teams Meeting",
    ActivityDate: "2026-07-05T14:30:00",
    Subject: "Cross-site technical lead transition",
    Summary: "Elena elevated to cross-site Technical Lead on Thermal Recovery Line.",
    ActivityDescription:
      "Leadership alignment on PL-1031 commissioning. Elena elevated to cross-site Technical Lead covering Thermal Recovery Line scope.",
    Company: { Id: 1, Title: "Nordic Polymers AB" },
    Contact: { Id: 101, Title: "Elena Lindström" },
    Deal: { Id: 0, Title: "PL-1031" },
    ActivityOwner: { Id: 24, Title: "Maya Chen" },
    ActionRequired: true,
    NextAction: "Update deal team assignments",
    NextActionDate: "2026-07-08",
    ActionStatus: "Completed",
    ActionOutcome: "Neutral",
    KeyDecisions: [
      "Elena Lindström assumes Technical Lead across PL-1031",
      "Weekly sync moved to Tuesdays 14:00 CET",
    ],
    AgreedActions: [{ text: "HR to update project roster by Friday" }],
    Risks: ["Handover window overlaps with site audit week"],
    LinkedDeals: [{ Id: 0, Title: "PL-1031" }],
    LinkedContacts: [{ Id: 101, Title: "Elena Lindström" }],
  },
  {
    id: 4,
    ActivityID: "ACT-9004",
    ActivityType: "Technical Review",
    ActivityDate: "2026-07-05T11:00:00",
    Subject: "Mixed-plastics feedstock variance audit",
    Summary: "Compliance audit flagged mixed-plastics variance on PL-1031 route.",
    ActivityDescription:
      "Compliance audit note filed for mixed-plastics feedstock variance on PL-1031 recovery route. Moisture spikes correlated with supplier batch change.",
    Company: { Id: 1, Title: "Nordic Polymers AB" },
    Contact: { Id: 101, Title: "Elena Lindström" },
    Deal: { Id: 0, Title: "PL-1031" },
    ActivityOwner: { Id: 12, Title: "Elena Lindström" },
    ActionRequired: true,
    NextAction: "Schedule site sampling visit",
    NextActionDate: "2026-07-04",
    ActionStatus: "Open",
    ActionOutcome: "Pending",
    KeyDecisions: ["Pause non-conforming batches until sampling complete"],
    AgreedActions: [
      { text: "Compliance to issue formal audit memo", status: "In Progress" },
    ],
    Risks: [
      "Potential commissioning delay if variance persists",
      "Regulatory exposure if documentation incomplete",
    ],
    LinkedDocuments: [
      {
        Title: "PL-1031_Audit-Note.03.pdf",
        DocCategory: "Compliance",
        Revision: "03",
        DealId: "PL-1031",
      },
    ],
    LinkedDeals: [{ Id: 0, Title: "PL-1031" }],
    LinkedContacts: [{ Id: 101, Title: "Elena Lindström" }],
  },
  {
    id: 5,
    ActivityID: "ACT-9005",
    ActivityType: "Proposal Sent",
    ActivityDate: "2026-07-04T16:20:00",
    Subject: "Q3 financial invoice and SmartDocs upload",
    Summary: "Financial invoice uploaded and auto-renamed via SmartDocs.",
    ActivityDescription:
      "Financial invoice auto-renamed to PL-1042_Financial-Invoice.01 Q3 Report.pdf via Gemini parse. Sent to client accounts payable.",
    Company: { Id: 1, Title: "Nordic Polymers AB" },
    Contact: { Id: 101, Title: "Elena Lindström" },
    Deal: { Id: 0, Title: "PL-1042" },
    ActivityOwner: { Id: 12, Title: "Elena Lindström" },
    ActionRequired: false,
    NextAction: "",
    NextActionDate: "",
    ActionStatus: "Completed",
    ActionOutcome: "Neutral",
    KeyDecisions: ["Invoice accepted into SmartDocs financial category"],
    LinkedDocuments: [
      {
        Title: "PL-1042_Financial-Invoice.01 Q3 Report.pdf",
        DocCategory: "Financial",
        Revision: "01",
        DealId: "PL-1042",
      },
    ],
    LinkedDeals: [{ Id: 0, Title: "PL-1042" }],
    LinkedContacts: [{ Id: 101, Title: "Elena Lindström" }],
  },
  {
    id: 6,
    ActivityID: "ACT-9006",
    ActivityType: "Site Visit",
    ActivityDate: "2026-07-03T10:00:00",
    Subject: "Portland textile recovery facility tour",
    Summary: "Confirmed feedstock sorting capacity meets reactor intake spec.",
    ActivityDescription:
      "Walked the Circular Textiles recovery line with Maya. Confirmed feedstock sorting capacity meets reactor intake spec for PL-1038 commissioning.",
    Company: { Id: 2, Title: "Circular Textiles Co." },
    Contact: { Id: 201, Title: "Maya Chen" },
    Deal: { Id: 0, Title: "PL-1038" },
    ActivityOwner: { Id: 24, Title: "Maya Chen" },
    ActionRequired: true,
    NextAction: "Send commissioning timeline draft",
    NextActionDate: "2026-07-10",
    ActionStatus: "In Progress",
    ActionOutcome: "Positive",
    KeyDecisions: [
      "Site ready for reactor delivery window in August",
      "Sorting line upgrade deferred to Phase 2",
    ],
    AgreedActions: [{ text: "Engineering to validate intake conveyor throughput" }],
    Risks: ["Weather may delay exterior foundation work"],
    LinkedDeals: [{ Id: 0, Title: "PL-1038" }],
    LinkedContacts: [{ Id: 201, Title: "Maya Chen" }],
  },
  {
    id: 7,
    ActivityID: "ACT-9007",
    ActivityType: "Meeting",
    ActivityDate: "2026-07-02T15:00:00",
    Subject: "Legacy Materials prospecting discovery",
    Summary: "High interest in pyrolysis pilot — feasibility assessment requested.",
    ActivityDescription:
      "Initial discovery with James Holloway on waste management partnership. High interest in pyrolysis pilot for municipal waste stream.",
    Company: { Id: 4, Title: "Legacy Materials Ltd." },
    Contact: { Id: 401, Title: "James Holloway" },
    Deal: { Id: 0, Title: "PL-1019" },
    ActivityOwner: { Id: 41, Title: "James Holloway" },
    ActionRequired: true,
    NextAction: "Prepare feasibility assessment",
    NextActionDate: "2026-07-15",
    ActionStatus: "Open",
    ActionOutcome: "Positive",
    KeyDecisions: ["Proceed to feasibility stage for PL-1019"],
    AgreedActions: [
      { text: "James to share waste composition data", dueDate: "2026-07-08" },
      { text: "Commercial to draft pilot commercial terms", status: "Open" },
    ],
    Risks: ["Budget approval cycle may extend into Q4"],
    LinkedDeals: [{ Id: 0, Title: "PL-1019" }],
    LinkedContacts: [{ Id: 401, Title: "James Holloway" }],
  },
  {
    id: 8,
    ActivityID: "ACT-9008",
    ActivityType: "Email",
    ActivityDate: "2026-07-01T08:30:00",
    Subject: "Reclaim Industries reactor delivery update",
    Summary: "Foundation concrete poured on schedule — vessel delivery on track for August.",
    ActivityDescription:
      "Sofia confirmed foundation concrete poured on schedule. Vessel delivery on track for August. No change to commissioning milestone.",
    Company: { Id: 3, Title: "Reclaim Industries" },
    Contact: { Id: 301, Title: "Sofia Marchetti" },
    Deal: { Id: 0, Title: "PL-1027" },
    ActivityOwner: { Id: 31, Title: "Sofia Marchetti" },
    ActionRequired: false,
    NextAction: "",
    NextActionDate: "",
    ActionStatus: "Completed",
    ActionOutcome: "Positive",
    KeyDecisions: ["August delivery window confirmed"],
    LinkedDeals: [{ Id: 0, Title: "PL-1027" }],
    LinkedContacts: [{ Id: 301, Title: "Sofia Marchetti" }],
  },
];

/** @deprecated Use defaultActivities from @/lib/activities-data */
export { defaultActivities as defaultInteractions } from "@/lib/activities-data";
