import type { CommercialPackage } from "@/types/commercial-package";
import { generateDocumentSetId } from "@/lib/document-set-engine";

/**
 * Seed commercial baseline chain for PL-1031 — demonstrates send → accept → execute
 * without email or folder search.
 */
export const defaultCommercialPackages: CommercialPackage[] = [
  {
    id: 1,
    PackageID: "PKG-9001",
    DocumentSetID: "PI-001",
    DealId: "PL-1031",
    ClientName: "Carbon Emergente",
    kind: "price_indication",
    status: "superseded",
    title: "Price Indication — Thermal Recovery Reactor",
    CreatedAt: "2026-03-10T09:00:00+01:00",
    CreatedBy: "SmartCRM Commercial",
    members: [
      {
        role: "quotation",
        Title: "PL-1031_Commercial-Price Indication.01 Budgetary Offer.pdf",
        fileName: "PL-1031_Commercial-Price Indication.01 Budgetary Offer.pdf",
        DocCategory: "Commercial",
        Revision: "01",
        DealId: "PL-1031",
      },
      {
        role: "technical",
        Title: "PL-1031_Technical-Process Summary.01.pdf",
        fileName: "PL-1031_Technical-Process Summary.01.pdf",
        DocCategory: "Technical",
        Revision: "01",
        DealId: "PL-1031",
      },
    ],
    summary: "Initial budgetary envelope for recovery line capacity.",
  },
  {
    id: 2,
    PackageID: "PKG-9002",
    DocumentSetID: "BQ-001",
    DealId: "PL-1031",
    ClientName: "Carbon Emergente",
    kind: "budget_quotation",
    status: "superseded",
    title: "Budget Quotation — Thermal Recovery Reactor",
    CreatedAt: "2026-04-05T11:30:00+02:00",
    CreatedBy: "SmartCRM Commercial",
    members: [
      {
        role: "quotation",
        Title: "PL-1031_Commercial-Budget Quotation.02 Scope Budget.pdf",
        fileName: "PL-1031_Commercial-Budget Quotation.02 Scope Budget.pdf",
        DocCategory: "Commercial",
        Revision: "02",
        DealId: "PL-1031",
      },
      {
        role: "attachment",
        Title: "PL-1031_Commercial-Budget Appendix.02 Feedstock Assumptions.pdf",
        fileName: "PL-1031_Commercial-Budget Appendix.02 Feedstock Assumptions.pdf",
        DocCategory: "Commercial",
        Revision: "02",
        DealId: "PL-1031",
      },
      {
        role: "technical",
        Title: "PL-1031_Technical-Heat Balance.02.pdf",
        fileName: "PL-1031_Technical-Heat Balance.02.pdf",
        DocCategory: "Technical",
        Revision: "02",
        DealId: "PL-1031",
      },
    ],
    summary: "Scoped budget quotation with feedstock and heat-balance assumptions.",
  },
  {
    id: 3,
    PackageID: "PKG-9003",
    DocumentSetID: "FQ-001",
    DealId: "PL-1031",
    ClientName: "Carbon Emergente",
    kind: "formal_quotation",
    status: "accepted",
    title: "Formal Quotation — Thermal Recovery Reactor",
    CreatedAt: "2026-05-18T14:00:00+02:00",
    CreatedBy: "SmartCRM Commercial",
    members: [
      {
        role: "quotation",
        Title: "PL-1031_Commercial-Formal Quotation.03 Firm Offer.pdf",
        fileName: "PL-1031_Commercial-Formal Quotation.03 Firm Offer.pdf",
        DocCategory: "Commercial",
        Revision: "03",
        DealId: "PL-1031",
      },
      {
        role: "attachment",
        Title: "PL-1031_Commercial-Terms Schedule.03.pdf",
        fileName: "PL-1031_Commercial-Terms Schedule.03.pdf",
        DocCategory: "Commercial",
        Revision: "03",
        DealId: "PL-1031",
      },
      {
        role: "technical",
        Title: "PL-1031_Technical-Technical Datasheet.01 Recovery Specs.pdf",
        fileName: "PL-1031_Technical-Technical Datasheet.01 Recovery Specs.pdf",
        DocCategory: "Technical",
        Revision: "01",
        DealId: "PL-1031",
      },
      {
        role: "commercial",
        Title: "PL-1031_Commercial-Payment Milestones.03.pdf",
        fileName: "PL-1031_Commercial-Payment Milestones.03.pdf",
        DocCategory: "Commercial",
        Revision: "03",
        DealId: "PL-1031",
      },
    ],
    summary: "Firm commercial offer with terms, specs, and payment milestones.",
  },
  {
    id: 4,
    PackageID: "PKG-9004",
    DocumentSetID: "TX-001",
    DealId: "PL-1031",
    ClientName: "Carbon Emergente",
    kind: "transmission",
    status: "frozen",
    title: "Transmission — Formal Quotation Rev 03",
    CreatedAt: "2026-06-12T09:30:00+02:00",
    CreatedBy: "Mats Borgersen",
    parentPackageId: "PKG-9003",
    recipient: "Elena Lindström <e.lindstrom@carbonemergente.com>",
    sentAt: "2026-06-12T09:30:00+02:00",
    members: [
      {
        role: "quotation",
        Title: "PL-1031_Commercial-Formal Quotation.03 Firm Offer.pdf",
        fileName: "PL-1031_Commercial-Formal Quotation.03 Firm Offer.pdf",
        DocCategory: "Commercial",
        Revision: "03",
        DealId: "PL-1031",
      },
      {
        role: "attachment",
        Title: "PL-1031_Commercial-Terms Schedule.03.pdf",
        fileName: "PL-1031_Commercial-Terms Schedule.03.pdf",
        DocCategory: "Commercial",
        Revision: "03",
        DealId: "PL-1031",
      },
      {
        role: "technical",
        Title: "PL-1031_Technical-Technical Datasheet.01 Recovery Specs.pdf",
        fileName: "PL-1031_Technical-Technical Datasheet.01 Recovery Specs.pdf",
        DocCategory: "Technical",
        Revision: "01",
        DealId: "PL-1031",
      },
      {
        role: "commercial",
        Title: "PL-1031_Commercial-Payment Milestones.03.pdf",
        fileName: "PL-1031_Commercial-Payment Milestones.03.pdf",
        DocCategory: "Commercial",
        Revision: "03",
        DealId: "PL-1031",
      },
    ],
    summary: "Frozen send package — exact files and revisions transmitted to customer.",
  },
  {
    id: 5,
    PackageID: "PKG-9005",
    DocumentSetID: "CB-001",
    DealId: "PL-1031",
    ClientName: "Carbon Emergente",
    kind: "commercial_baseline",
    status: "frozen",
    title: "Commercial Baseline — PL-1031 Accepted Offer",
    CreatedAt: "2026-06-28T14:15:00+02:00",
    CreatedBy: "SmartCRM Commercial",
    parentPackageId: "PKG-9004",
    acceptedAt: "2026-06-28T14:15:00+02:00",
    members: [
      {
        role: "quotation",
        Title: "PL-1031_Commercial-Formal Quotation.03 Firm Offer.pdf",
        fileName: "PL-1031_Commercial-Formal Quotation.03 Firm Offer.pdf",
        DocCategory: "Commercial",
        Revision: "03",
        DealId: "PL-1031",
      },
      {
        role: "attachment",
        Title: "PL-1031_Commercial-Terms Schedule.03.pdf",
        fileName: "PL-1031_Commercial-Terms Schedule.03.pdf",
        DocCategory: "Commercial",
        Revision: "03",
        DealId: "PL-1031",
      },
      {
        role: "technical",
        Title: "PL-1031_Technical-Technical Datasheet.01 Recovery Specs.pdf",
        fileName: "PL-1031_Technical-Technical Datasheet.01 Recovery Specs.pdf",
        DocCategory: "Technical",
        Revision: "01",
        DealId: "PL-1031",
      },
      {
        role: "commercial",
        Title: "PL-1031_Commercial-Payment Milestones.03.pdf",
        fileName: "PL-1031_Commercial-Payment Milestones.03.pdf",
        DocCategory: "Commercial",
        Revision: "03",
        DealId: "PL-1031",
      },
    ],
    summary: "Accepted quotation, attachments, specifications, and commercial terms.",
  },
  {
    id: 6,
    PackageID: "PKG-9006",
    DocumentSetID: "EX-001",
    DealId: "PL-1031",
    ClientName: "Carbon Emergente",
    kind: "execution",
    status: "frozen",
    title: "Execution Package — PL-1031 Won",
    CreatedAt: "2026-07-01T10:00:00+02:00",
    CreatedBy: "SmartCRM Delivery",
    parentPackageId: "PKG-9005",
    members: [
      {
        role: "quotation",
        Title: "PL-1031_Commercial-Formal Quotation.03 Firm Offer.pdf",
        fileName: "PL-1031_Commercial-Formal Quotation.03 Firm Offer.pdf",
        DocCategory: "Commercial",
        Revision: "03",
        DealId: "PL-1031",
      },
      {
        role: "commercial",
        Title: "PL-1031_Legal-Signed Contract.01 Executed Agreement.pdf",
        fileName: "PL-1031_Legal-Signed Contract.01 Executed Agreement.pdf",
        DocCategory: "Legal",
        Revision: "01",
        DealId: "PL-1031",
      },
      {
        role: "attachment",
        Title: "PL-1031_Commercial-Customer Contacts.01 Project Roster.pdf",
        fileName: "PL-1031_Commercial-Customer Contacts.01 Project Roster.pdf",
        DocCategory: "Commercial",
        Revision: "01",
        DealId: "PL-1031",
      },
      {
        role: "technical",
        Title: "PL-1031_Technical-Clarifications.01 Engineering Notes.pdf",
        fileName: "PL-1031_Technical-Clarifications.01 Engineering Notes.pdf",
        DocCategory: "Technical",
        Revision: "01",
        DealId: "PL-1031",
      },
    ],
    summary: "Baseline + signed contract + customer contacts + meeting clarifications.",
  },
];
