import type { Company, Contact } from "@/types/company";
import type { ContactListRole } from "@/types/contact";
import { buildContactTitle } from "@/types/contact";

export type { Company, Contact, CompanyIndustry, CompanyStatus } from "@/types/company";
export { COMPANY_INDUSTRIES, COMPANY_INDUSTRY_GROUPS, COMPANY_STATUSES, formatCompanyLocation, resolveCompanyIndustry } from "@/types/company";

function contact(
  id: number,
  ContactID: string,
  FirstName: string,
  LastName: string,
  company: Pick<Company, "id" | "Title">,
  Role: ContactListRole,
  Email: string,
  Phone: string,
  extras?: Partial<
    Pick<Contact, "Mobile" | "LinkedInURL" | "Status" | "RelationshipLevel" | "JobTitle">
  >,
): Contact {
  return {
    id,
    ContactID,
    Title: buildContactTitle(FirstName, LastName),
    FirstName,
    LastName,
    Company: { Id: company.id, Title: company.Title },
    JobTitle: extras?.JobTitle ?? Role,
    Role,
    Email,
    Phone,
    Mobile: extras?.Mobile ?? "",
    LinkedInURL: extras?.LinkedInURL ?? "",
    Status: extras?.Status ?? "Active",
    RelationshipLevel: extras?.RelationshipLevel ?? "Operational",
  };
}

const nordic = { id: 1, Title: "Nordic Polymers AB" };
const circular = { id: 2, Title: "Circular Textiles Co." };
const reclaim = { id: 3, Title: "Reclaim Industries" };
const legacy = { id: 4, Title: "Legacy Materials Ltd." };
const upcycle = { id: 5, Title: "Upcycle Alliance Group" };

export const defaultCompanies: Company[] = [
  {
    id: 1,
    Title: "Nordic Polymers AB",
    CompanyID: "CO-1001",
    ParentCompany: { Id: 5, Title: "Upcycle Alliance Group" },
    Domain: "nordicpolymers.se",
    Industry: "Polymer Processing",
    Status: "Active",
    AccountOwner: { Id: 1, Title: "Mats Borgersen" },
    Phone: "+46 8 555 0100",
    Email: "info@nordicpolymers.se",
    AddressLine1: "Industrigatan 14",
    AddressLine2: "Building C",
    PostalCode: "112 46",
    City: "Stockholm",
    Country: { Id: 752, Title: "Sweden" },
    pipelineIds: ["PL-1042", "PL-1031"],
    contacts: [
      contact(
        101,
        "CT-10011",
        "Elena",
        "Lindström",
        nordic,
        "Plant Manager",
        "elena.lindstrom@nordicpolymers.se",
        "+46 8 555 0122",
        {
          Mobile: "+46 70 555 0122",
          LinkedInURL: "https://www.linkedin.com/in/elena-lindstrom",
          RelationshipLevel: "Strategic",
        },
      ),
      contact(
        102,
        "CT-10012",
        "Jonas",
        "Berg",
        nordic,
        "Procurement",
        "jonas.berg@nordicpolymers.se",
        "+46 8 555 0198",
        { Mobile: "+46 70 555 0198", RelationshipLevel: "Operational" },
      ),
    ],
  },
  {
    id: 2,
    Title: "Circular Textiles Co.",
    CompanyID: "CO-1002",
    ParentCompany: null,
    Domain: "circulartextiles.com",
    Industry: "Textile Recovery",
    Status: "Contracted",
    AccountOwner: { Id: 1, Title: "Mats Borgersen" },
    Phone: "+1 503 555 2200",
    Email: "",
    AddressLine1: "2400 NW Industrial Way",
    AddressLine2: "",
    PostalCode: "97210",
    City: "Portland",
    Country: { Id: 840, Title: "United States" },
    pipelineIds: ["PL-1038"],
    contacts: [
      contact(
        201,
        "CT-10021",
        "Maya",
        "Chen",
        circular,
        "Plant Manager",
        "maya.chen@circulartextiles.com",
        "+1 503 555 2210",
        { RelationshipLevel: "Strategic" },
      ),
      contact(
        202,
        "CT-10022",
        "David",
        "Okonkwo",
        circular,
        "Procurement",
        "david.okonkwo@circulartextiles.com",
        "+1 503 555 2244",
      ),
    ],
  },
  {
    id: 3,
    Title: "Reclaim Industries",
    CompanyID: "CO-1003",
    ParentCompany: null,
    Domain: "reclaimind.com",
    Industry: "Chemical Manufacturing",
    Status: "Active",
    AccountOwner: { Id: 1, Title: "Mats Borgersen" },
    Phone: "+39 02 555 8800",
    Email: "",
    AddressLine1: "Via dell'Industria 8",
    AddressLine2: "",
    PostalCode: "20124",
    City: "Milan",
    Country: { Id: 380, Title: "Italy" },
    pipelineIds: ["PL-1027"],
    contacts: [
      contact(
        301,
        "CT-10031",
        "Sofia",
        "Marchetti",
        reclaim,
        "Plant Manager",
        "sofia.marchetti@reclaimind.com",
        "+39 02 555 8831",
        { RelationshipLevel: "Strategic" },
      ),
    ],
  },
  {
    id: 4,
    Title: "Legacy Materials Ltd.",
    CompanyID: "CO-1004",
    ParentCompany: null,
    Domain: "legacymaterials.co.uk",
    Industry: "Waste Management",
    Status: "Prospecting",
    AccountOwner: { Id: 1, Title: "Mats Borgersen" },
    Phone: "+44 161 555 3300",
    Email: "",
    AddressLine1: "Trafford Park Estate",
    AddressLine2: "Unit 7",
    PostalCode: "M17 1HH",
    City: "Manchester",
    Country: { Id: 826, Title: "United Kingdom" },
    pipelineIds: ["PL-1019"],
    contacts: [
      contact(
        401,
        "CT-10041",
        "James",
        "Holloway",
        legacy,
        "Executive Sponsor",
        "james.holloway@legacymaterials.co.uk",
        "+44 161 555 3302",
        { RelationshipLevel: "Strategic" },
      ),
      contact(
        402,
        "CT-10042",
        "Priya",
        "Nair",
        legacy,
        "Compliance Officer",
        "priya.nair@legacymaterials.co.uk",
        "+44 161 555 3318",
        { RelationshipLevel: "Tactical" },
      ),
    ],
  },
  {
    id: 5,
    Title: "Upcycle Alliance Group",
    CompanyID: "CO-1005",
    ParentCompany: null,
    Domain: "upcyclealliance.com",
    Industry: "Energy & Infrastructure",
    Status: "Active",
    AccountOwner: { Id: 1, Title: "Mats Borgersen" },
    Phone: "+1 312 555 9000",
    Email: "",
    AddressLine1: "500 W Monroe St",
    AddressLine2: "Suite 2400",
    PostalCode: "60661",
    City: "Chicago",
    Country: { Id: 840, Title: "United States" },
    pipelineIds: ["PL-1042", "PL-1038", "PL-1031"],
    contacts: [
      contact(
        501,
        "CT-10051",
        "Amir",
        "Hassan",
        upcycle,
        "Executive Sponsor",
        "amir.hassan@upcyclealliance.com",
        "+1 312 555 9044",
        { RelationshipLevel: "Strategic" },
      ),
      contact(
        502,
        "CT-10052",
        "Claire",
        "Dubois",
        upcycle,
        "Procurement",
        "claire.dubois@upcyclealliance.com",
        "+1 312 555 9071",
        { RelationshipLevel: "Vendor" },
      ),
    ],
  },
];
