import type { PipelineRow } from "@/types/pipeline";

export const initialPipelines: PipelineRow[] = [
  {
    id: "PL-1042",
    assetName: "Nordic Pyrolysis Unit A",
    companyRole: "Technology Buyer",
    targetFeedstock: "HDPE",
    reactorDesignCapacity: 1240,
    currentMilestone: "Continuous Feed Verified",
    status: "Live Production",
    salesValue: 3200000,
    currency: "EUR",
    probability: 85,
    expectedCloseDate: "2026-08-30",
    offeringIds: [
      "sys-complete-turnkey-pyrolysis",
      "prod-pyrolysis-reactor",
      "prod-sb-control",
      "svc-aftermarket",
    ],
    team: [{ contactId: "CT-10011", projectRole: "Deal Sponsor" }],
  },
  {
    id: "PL-1038",
    assetName: "Circular Fiber Reactor",
    companyRole: "Feedstock Supplier",
    targetFeedstock: "Mixed Textile",
    reactorDesignCapacity: 860,
    currentMilestone: "Pre-heating Trial",
    status: "Commissioning Phase",
    salesValue: 1850000,
    currency: "USD",
    probability: 72,
    expectedCloseDate: "2026-07-12",
    offeringIds: [
      "prod-pyrolysis-reactor",
      "prod-material-reception",
      "prod-dryer",
      "svc-product-validation",
    ],
  },
  {
    id: "PL-1031",
    assetName: "Thermal Recovery Reactor",
    companyRole: "Technology Buyer",
    targetFeedstock: "Mixed Plastics",
    reactorDesignCapacity: 2100,
    currentMilestone: "Reactor Vessel Delivered",
    status: "Site Installation",
    salesValue: 4100000,
    currency: "EUR",
    probability: 68,
    expectedCloseDate: "2026-06-20",
    offeringIds: [
      "prod-pyrolysis-reactor",
      "prod-heat-recovery",
      "prod-post-treatment",
      "svc-project-development-fel2-fel3",
    ],
  },
  {
    id: "PL-1027",
    assetName: "Flake Sorting Pyrolysis Cell",
    companyRole: "Off-take Partner",
    targetFeedstock: "PET",
    reactorDesignCapacity: 540,
    currentMilestone: "Foundation Concrete Poured",
    status: "Reactor Manufacturing",
    salesValue: 980000,
    currency: "NOK",
    probability: 54,
    expectedCloseDate: "2026-09-15",
    offeringIds: [
      "prod-material-qualification",
      "prod-buffer-systems",
      "prod-packaging",
      "svc-product-validation",
    ],
  },
  {
    id: "PL-1019",
    assetName: "Legacy Extrusion Retrofit",
    companyRole: "Infrastructure Partner",
    targetFeedstock: "PP Reclaim",
    reactorDesignCapacity: 0,
    currentMilestone: "Heat Exchanger Rebuild",
    status: "Scheduled Maintenance",
    salesValue: 420000,
    currency: "EUR",
    probability: 35,
    expectedCloseDate: "2026-10-01",
    offeringIds: [
      "prod-sb-control",
      "prod-sb-cloud-service",
      "prod-sb-reporting-service",
      "svc-aftermarket",
      "svc-sb-production-planner",
    ],
  },
];
