import {
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  TextRun,
  type ISectionOptions,
} from "docx";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { ResearchReport, ResearchReportExportFormat } from "@/types/research-report";

const BRAND = {
  primary: "#1a365d",
  accent: "#e85d04",
  muted: "#64748b",
};

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function reportHtml(report: ResearchReport, mode: "export" | "sharepoint" = "export"): string {
  const sections = report.sections
    .map((section) => {
      const paragraphs = section.paragraphs
        .map((p) => `<p>${escapeHtml(p)}</p>`)
        .join("");
      const bullets =
        section.bullets.length > 0
          ? `<ul>${section.bullets
              .map(
                (b) =>
                  `<li><strong>${escapeHtml(b.label)}</strong>${b.detail ? ` — ${escapeHtml(b.detail)}` : ""}</li>`,
              )
              .join("")}</ul>`
          : "";
      return `<section><h2>${escapeHtml(section.title)}</h2>${paragraphs}${bullets}</section>`;
    })
    .join("");

  const sharePointBanner =
    mode === "sharepoint"
      ? `<div class="sp-banner">SharePoint · SmartCRM Knowledge Platform · ${escapeHtml(report.metadata.sharePointPath)}</div>`
      : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(report.title)}</title>
  <style>
    body { font-family: "Segoe UI", Arial, sans-serif; color: #0f172a; max-width: 800px; margin: 2rem auto; line-height: 1.5; }
    h1 { color: ${BRAND.primary}; font-size: 1.5rem; margin-bottom: 0.25rem; }
    .meta { color: ${BRAND.muted}; font-size: 0.85rem; margin-bottom: 1.5rem; }
    h2 { color: ${BRAND.primary}; font-size: 1rem; margin-top: 1.5rem; border-bottom: 1px solid #e2e8f0; padding-bottom: 0.25rem; }
    ul { padding-left: 1.25rem; }
    li { margin-bottom: 0.35rem; }
    .sp-banner { background: #f1f5f9; padding: 0.75rem 1rem; border-radius: 6px; font-size: 0.8rem; margin-bottom: 1rem; }
    .assessment { background: #fff7ed; border-left: 4px solid ${BRAND.accent}; padding: 0.75rem 1rem; margin-top: 1rem; }
    @media print { body { margin: 1cm; } }
  </style>
</head>
<body>
  ${sharePointBanner}
  <h1>${escapeHtml(report.title)}</h1>
  <p class="meta">${escapeHtml(report.typeLabel)} · ${escapeHtml(report.subject)} · ${new Date(report.generatedAt).toLocaleString("en-GB")} · Rev ${report.revision}</p>
  <p class="meta">DocCategory: ${report.docCategory} · DocType: ${escapeHtml(report.docType)} · Generated by ${escapeHtml(report.metadata.generatedBy)}</p>
  ${sections}
  <div class="assessment">
    <strong>Strategic Assessment:</strong> ${escapeHtml(report.priority.toUpperCase())} — ${escapeHtml(report.strategicPriority)}
  </div>
</body>
</html>`;
}

export function buildResearchReportHtml(
  report: ResearchReport,
  format: "pdf" | "sharepoint" = "pdf",
): string {
  return reportHtml(report, format === "sharepoint" ? "sharepoint" : "export");
}

export async function buildResearchReportDocx(report: ResearchReport): Promise<Buffer> {
  const children: Paragraph[] = [
    new Paragraph({
      text: report.title,
      heading: HeadingLevel.TITLE,
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: `${report.typeLabel} · ${report.subject} · ${new Date(report.generatedAt).toLocaleString("en-GB")}`,
          color: "64748B",
          size: 20,
        }),
      ],
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: `DocCategory: ${report.docCategory} · DocType: ${report.docType} · Rev ${report.revision}`,
          color: "64748B",
          size: 18,
        }),
      ],
    }),
    new Paragraph({ text: "" }),
  ];

  for (const section of report.sections) {
    children.push(
      new Paragraph({ text: section.title, heading: HeadingLevel.HEADING_1 }),
    );
    for (const paragraph of section.paragraphs) {
      children.push(new Paragraph({ text: paragraph }));
    }
    for (const bullet of section.bullets) {
      children.push(
        new Paragraph({
          text: bullet.detail ? `${bullet.label} — ${bullet.detail}` : bullet.label,
          bullet: { level: 0 },
        }),
      );
    }
  }

  children.push(
    new Paragraph({ text: "Strategic Assessment", heading: HeadingLevel.HEADING_1 }),
    new Paragraph({
      text: `${report.priority.toUpperCase()} — ${report.strategicPriority}`,
    }),
  );

  const doc = new Document({
    sections: [{ children } satisfies ISectionOptions],
    creator: "SmartAssist",
    title: report.title,
    description: report.typeLabel,
  });

  return Packer.toBuffer(doc);
}

export async function buildResearchReportPdf(report: ResearchReport): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const pageWidth = 595;
  const pageHeight = 842;
  const margin = 50;
  const lineHeight = 14;
  const maxWidth = pageWidth - margin * 2;

  let page = pdf.addPage([pageWidth, pageHeight]);
  let y = pageHeight - margin;

  function wrapText(text: string, size: number, bold = false): string[] {
    const words = text.split(/\s+/);
    const lines: string[] = [];
    let current = "";
    const f = bold ? fontBold : font;

    for (const word of words) {
      const test = current ? `${current} ${word}` : word;
      if (f.widthOfTextAtSize(test, size) <= maxWidth) {
        current = test;
      } else {
        if (current) lines.push(current);
        current = word;
      }
    }
    if (current) lines.push(current);
    return lines.length > 0 ? lines : [""];
  }

  function ensureSpace(linesNeeded: number) {
    if (y - linesNeeded * lineHeight < margin) {
      page = pdf.addPage([pageWidth, pageHeight]);
      y = pageHeight - margin;
    }
  }

  function drawLine(text: string, size: number, bold = false, color = rgb(0.06, 0.09, 0.16)) {
    const lines = wrapText(text, size, bold);
    ensureSpace(lines.length);
    const f = bold ? fontBold : font;
    for (const line of lines) {
      page.drawText(line, { x: margin, y, size, font: f, color });
      y -= lineHeight;
    }
  }

  drawLine(report.title, 14, true);
  drawLine(`${report.typeLabel} · ${report.subject}`, 9);
  drawLine(`Generated ${new Date(report.generatedAt).toLocaleString("en-GB")} · SmartAssist`, 8);
  y -= 8;

  for (const section of report.sections) {
    y -= 6;
    drawLine(section.title, 11, true, rgb(0.1, 0.21, 0.36));
    for (const paragraph of section.paragraphs) {
      drawLine(paragraph, 9);
    }
    for (const bullet of section.bullets) {
      drawLine(`• ${bullet.detail ? `${bullet.label} — ${bullet.detail}` : bullet.label}`, 9);
    }
  }

  y -= 8;
  drawLine(`Strategic Assessment: ${report.priority.toUpperCase()} — ${report.strategicPriority}`, 10, true);

  return pdf.save();
}

export function exportFilename(report: ResearchReport, format: ResearchReportExportFormat): string {
  const base = report.reportId;
  switch (format) {
    case "docx":
      return `${base}_${report.docType.replace(/\s+/g, "-")}.docx`;
    case "pdf":
      return `${base}_${report.docType.replace(/\s+/g, "-")}.pdf`;
    case "sharepoint":
      return `${base}_SharePoint-Page.html`;
  }
}

export function exportContentType(format: ResearchReportExportFormat): string {
  switch (format) {
    case "docx":
      return "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
    case "pdf":
      return "application/pdf";
    case "sharepoint":
      return "text/html; charset=utf-8";
  }
}

export async function buildResearchReportExport(
  report: ResearchReport,
  format: ResearchReportExportFormat,
): Promise<Buffer | Uint8Array | string> {
  switch (format) {
    case "docx":
      return buildResearchReportDocx(report);
    case "pdf":
      return buildResearchReportPdf(report);
    case "sharepoint":
      return buildResearchReportHtml(report, "sharepoint");
  }
}
